### 테이블 불러오기 select편

In [3]:
import requests, bs4, pandas as pd, numpy as np
 
#웹페이지 html 소스 가져오기
resp = requests.get("http://finance.naver.com/marketindex/")
resp.encoding='utf-8'
html = resp.text

bs = bs4.BeautifulSoup(html, 'html.parser')

# 데이터 추출하기
price = bs.select_one("div.head_info > span.value").string
print("usd/krw= ", price)

# 리스트 초기화 및 데이터 담기
outList = []
outList.append(price)

# 리스트 pandas 데이터 프레임으로 변환 및 컬럼 정의
outDf = pd.DataFrame(np.array(outList).reshape(1,1))
outDf.columns = ['title']
# CSV 파일로 저장, encondig 한글깨짐 방지
#outDf.to_csv("../dataset/webData.csv", encoding='utf-8-sig',index=False)
outDf

usd/krw=  1,083.00

      title
0  1,083.00

In [4]:
###

In [5]:
import requests, bs4, pandas as pd, numpy as np
 
#웹페이지 html 소스 가져오기
resp = requests.get('http://13.209.33.89:3333/quiz')
resp.encoding='utf-8'
html = resp.text

bs = bs4.BeautifulSoup(html, "html.parser")
# div에서 id가 id_db_quiz인것만 추출
divs = bs.select("div#id_db_quiz")
print(divs)

[<div class="class_db_quiz" id="id_db_quiz">
<h1>데이터베이스 퀴즈 </h1>
<a href="https://docs.google.com/forms/d/e/1FAIpQLSff5TjqUq9u-jRxYZvTdB7k-N0AEjx0_WSIcLZCBfFiEfoRUA/viewform?usp=sf_link"> 6/12 오라클 Join 퀴즈 </a>
<p></p>
<a href="https://docs.google.com/forms/d/e/1FAIpQLScP3ojzBNFbKbTFq4r58GqqZODYom1d6jrn09rmdqT57uByVA/viewform?usp=sf_link"> 6/5 오라클 GroupBy 퀴즈 </a>
<p></p>
<a href="https://docs.google.com/forms/d/e/1FAIpQLSfU5Pv_GQOLV-SkrDirOGt4GLDP3sZpy-UPY4zsud2ODPknbA/viewform?usp=sf_link"> 5/29 오라클 숫자/날짜 및 고급함수 </a>
<p></p>
<a href="https://docs.google.com/forms/d/e/1FAIpQLSdFuYrwaYE6HEzQft21Icj_2yPyQqkcSabuvnaWwO47v99XmA/viewform?usp=sf_link"> 5/15 오라클 데이터 조회(함수활용)  </a>
<p></p>
<a href="https://docs.google.com/forms/d/e/1FAIpQLSd8MAsXIKIteOM4OFCggUoYeOqC5aGI-2aQFLV8533HkbTz-w/viewform?usp=sf_link"> 5/8 오라클 원격접속 및 조회 </a>
<p></p>
<a href="https://docs.google.com/forms/d/e/1FAIpQLSeYl0KM70XWhjnTIVLfqX5H5tp2V3jx2bwJMyZrTSeak2HZWw/viewform?usp=sf_link"> 4/10 무결성 제약조건 </a>
</div>]

In [6]:
####

In [10]:
import requests, bs4, pandas as pd, numpy as np
 
#웹페이지 html 소스 가져오기
resp = requests.get('http://13.209.33.89:3333/quiz')
resp.encoding='utf-8'
html = resp.text
bs = bs4.BeautifulSoup(html, "html.parser")
# div에서 class가 class_db_quiz인것만 추출 (1개)
seone = bs.select_one("div.class_db_quiz > a").string    
print(seone)

# div에서 class가 class_db_quiz인것만 추출 (다수)
divs = bs.select("div.class_db_quiz > a")
for li in divs:
    print(li.string)

 6/12 오라클 Join 퀴즈
 6/12 오라클 Join 퀴즈
 6/5 오라클 GroupBy 퀴즈
 5/29 오라클 숫자/날짜 및 고급함수
 5/15 오라클 데이터 조회(함수활용)
 5/8 오라클 원격접속 및 조회
 4/10 무결성 제약조건

In [11]:
###

In [1]:
import requests, bs4, pandas as pd, numpy as np
 
#웹페이지 html 소스 가져오기
resp = requests.get('http://13.209.33.89:3333/maps')
resp.encoding='utf-8'
html = resp.text
bs = bs4.BeautifulSoup(html, 'html.parser')

# html 부분구조 가져오기
columns=bs.select('table > thead > tr > th')
columns
type(columns)

columnlist=[]
for column in columns:
    columnlist.append(column.text)
df=pd.DataFrame(columns=columnlist)

df

Empty DataFrame
Columns: [geo_name, longitude, latitude, Action]
Index: []

In [3]:
contents=bs.select('table  > tbody > tr#trbody')
dfcontent=[]
alldfcontents=[]
for content in contents:
    tds=content.findAll("td")
    for td in tds:
        if(td.text=="None"):
            continue;
        dfcontent.append(td.text)
    alldfcontents.append(dfcontent)
    dfcontent=[]
df=pd.DataFrame(columns=columnlist, data=alldfcontents)
df

,geo_name,longitude,latitude,Action
0,polytech_kangseo2,126.840918,37.549506,\n\nEdit \n ...
1,coffeekorea_seulleng,127.0478832,37.50567504,\n\nEdit \n ...

### gitlist 목록을 스크랩하여 csv 파일로 추출하세요 pandas데이터목록으로 추출

In [14]:
import requests, bs4, pandas as pd, numpy as np
 
#웹페이지 html 소스 가져오기
resp = requests.get('http://13.209.33.89:3333/maps/gitList')
resp.encoding='utf-8'
html = resp.text
bs = bs4.BeautifulSoup(html, 'html.parser')

# html 부분구조 가져오기
columns=bs.select('table > tr > th')
columns
type(columns)

list

In [15]:
columnlist=[]
for column in columns:
    columnlist.append(column.text)
df=pd.DataFrame(columns=columnlist)

df

Empty DataFrame
Columns: [순번, 학생 이름, GIT 주소(뒷부분), 수정]
Index: []

In [20]:
contents=bs.select('table > tr#gitContents')
dfcontent=[]
alldfcontents=[]
contents

[<tr id="gitContents">
 <td>1</td>
 <td>KIM GANG RYONG</td>
 <td>wovmxl</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/1">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>2</td>
 <td>KIM DO WOON</td>
 <td>dowoonkim</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/2">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>3</td>
 <td>KIM EUI JIN</td>
 <td>doogn</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/3">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>4</td>
 <td>NOH YOUNG WOO</td>
 <td>ppoocoder</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/4">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>5</td>
 <td>PARK SEUNG JIN</td>
 <td>tmdwls</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/5">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>6</td>
 <td>SUNG HAN BIN</td>
 <td>sunghanbin</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/6">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>7</td>
 <td>SHIN SUNG WOO</td>
 <td>sinletsgo</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/7">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>8</td>
 <td>OH MI JIN</td>
 <td>ohmijin</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/8">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>9</td>
 <td>LEE DONG GEUN</td>
 <td>awd45</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/9">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>10</td>
 <td>LEE WOO SEOK</td>
 <td>creed35</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/10">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>11</td>
 <td>LEE EUN SIL</td>
 <td>milklandcoo</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/11">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>12</td>
 <td>LEE HAN MIN</td>
 <td>yumras</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/12">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>13</td>
 <td>LEE HYO JAE</td>
 <td>freespa</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/13">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>14</td>
 <td>JUNG KYUNG HWA</td>
 <td>JungKH89</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/14">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>15</td>
 <td>JEONG YU SEOCK</td>
 <td>jeongyuseoc</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/15">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>16</td>
 <td>JUNG HYO JAE</td>
 <td>jamiewell</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/16">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>17</td>
 <td>CHO DONG YEOK</td>
 <td>jody0406</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/17">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>18</td>
 <td>JO JEONG YEON</td>
 <td>hera7</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/18">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>19</td>
 <td>CHAE SUNG EUN</td>
 <td>sechae0528</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/19">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>20</td>
 <td>CHOI KYUNG JAE</td>
 <td>ckt9636</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/20">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>21</td>
 <td>CHOI DONG HUN</td>
 <td>MakeBelieve</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/21">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>22</td>
 <td>CHOI MIN SUNG</td>
 <td>sakurac0</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/22">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>23</td>
 <td>HA TAE YANG</td>
 <td>hataeyang</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/23">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>24</td>
 <td>YOON SUNG HO</td>
 <td>youtoo1116</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/24">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>25</td>
 <td>KIM JI SUNG</td>
 <td>binggugu</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/25">Edit</a>
                 </div>
 </td>
 </tr>, <tr id="gitContents">
 <td>26</td>
 <td>CHOI MIN HAN</td>
 <td>do not submit</td>
 <td>
 <div style="float:left">
 <a href="/maps/editgit/26">Edit</a>
                 </div>
 </td>
 </tr>]

In [21]:
for content in contents:
    tds=content.findAll("td")
    for td in tds:
        if(td.text=="None"):
            continue;
        dfcontent.append(td.text)
    alldfcontents.append(dfcontent)
    dfcontent=[]
df=pd.DataFrame(columns=columnlist, data=alldfcontents)
df

,순번,학생 이름,GIT 주소(뒷부분),수정
0,1,KIM GANG RYONG,wovmxl,\n\nEdit \r\n ...
1,2,KIM DO WOON,dowoonkim,\n\nEdit \r\n ...
2,3,KIM EUI JIN,doogn,\n\nEdit \r\n ...
3,4,NOH YOUNG WOO,ppoocoder,\n\nEdit \r\n ...
4,5,PARK SEUNG JIN,tmdwls,\n\nEdit \r\n ...
5,6,SUNG HAN BIN,sunghanbin,\n\nEdit \r\n ...
6,7,SHIN SUNG WOO,sinletsgo,\n\nEdit \r\n ...
7,8,OH MI JIN,ohmijin,\n\nEdit \r\n ...
8,9,LEE DONG GEUN,awd45,\n\nEdit \r\n ...
9,10,LEE WOO SEOK,creed35,\n\nEdit \r\n ...
10,11,LEE EUN SIL,milklandcoo,\n\nEdit \r\n ...
11,12,LEE HAN MIN,yumras,\n\nEdit \r\n ...
12,13,LEE HYO JAE,freespa,\n\nEdit \r\n ...
13,14,JUNG KYUNG HWA,JungKH89,\n\nEdit \r\n ...
14,15,JEONG YU SEOCK,jeongyuseoc,\n\nEdit \r\n ...
15,16,JUNG HYO JAE,jamiewell,\n\nEdit \r\n ...
16,17,CHO DONG YEOK,jody0406,\n\nEdit \r\n ...
17,18,JO JEONG YEON,hera7,\n\nEdit \r\n ...
18,19,CHAE SUNG EUN,sechae0528,\n\nEdit \r\n ...
19,20,CHOI KYUNG JAE,ckt9636,\n\nEdit \r\n ...
20,21,CHOI DONG HUN,MakeBelieve,\n\nEdit \r\n ...
21,22,CHOI MIN SUNG,sakurac0,\n\nEdit \r\n ...
22,23,HA TAE YANG,hataeyang,\n\nEdit \r\n ...
23,24,YOON SUNG HO,youtoo1116,\n\nEdit \r\n ...
24,25,KIM JI SUNG,binggugu,\n\nEdit \r\n ...
25,26,CHOI MIN HAN,do not submit,\n\nEdit \r\n ...

In [23]:
df.to_csv("../dataset/gitList.csv", encoding='utf-8-sig',index=False)
df

,순번,학생 이름,GIT 주소(뒷부분),수정
0,1,KIM GANG RYONG,wovmxl,\n\nEdit \r\n ...
1,2,KIM DO WOON,dowoonkim,\n\nEdit \r\n ...
2,3,KIM EUI JIN,doogn,\n\nEdit \r\n ...
3,4,NOH YOUNG WOO,ppoocoder,\n\nEdit \r\n ...
4,5,PARK SEUNG JIN,tmdwls,\n\nEdit \r\n ...
5,6,SUNG HAN BIN,sunghanbin,\n\nEdit \r\n ...
6,7,SHIN SUNG WOO,sinletsgo,\n\nEdit \r\n ...
7,8,OH MI JIN,ohmijin,\n\nEdit \r\n ...
8,9,LEE DONG GEUN,awd45,\n\nEdit \r\n ...
9,10,LEE WOO SEOK,creed35,\n\nEdit \r\n ...
10,11,LEE EUN SIL,milklandcoo,\n\nEdit \r\n ...
11,12,LEE HAN MIN,yumras,\n\nEdit \r\n ...
12,13,LEE HYO JAE,freespa,\n\nEdit \r\n ...
13,14,JUNG KYUNG HWA,JungKH89,\n\nEdit \r\n ...
14,15,JEONG YU SEOCK,jeongyuseoc,\n\nEdit \r\n ...
15,16,JUNG HYO JAE,jamiewell,\n\nEdit \r\n ...
16,17,CHO DONG YEOK,jody0406,\n\nEdit \r\n ...
17,18,JO JEONG YEON,hera7,\n\nEdit \r\n ...
18,19,CHAE SUNG EUN,sechae0528,\n\nEdit \r\n ...
19,20,CHOI KYUNG JAE,ckt9636,\n\nEdit \r\n ...
20,21,CHOI DONG HUN,MakeBelieve,\n\nEdit \r\n ...
21,22,CHOI MIN SUNG,sakurac0,\n\nEdit \r\n ...
22,23,HA TAE YANG,hataeyang,\n\nEdit \r\n ...
23,24,YOON SUNG HO,youtoo1116,\n\nEdit \r\n ...
24,25,KIM JI SUNG,binggugu,\n\nEdit \r\n ...
25,26,CHOI MIN HAN,do not submit,\n\nEdit \r\n ...